version: "3.8"

services:
    nginx-app:
        build: .
        volumes:
            - ./:/app
            - /app/node_modules # node_modules will be created in the container
        environment:
            - NODE_ENV=development

    nginx-server:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8085:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - nginx-app